name: test_against_lhapdf

on: [push]

jobs:
  lhatest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: lhconda
      - name: Install both lhapdf and lhapdf_management
        shell: bash -l {0}
        run: |
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
          conda config --append channels conda-forge
          conda install -y lhapdf
          python -m pip install .
          python -m pip install pytest
      - name: Test with pytest against lhapdf
        shell: bash -l {0}
        run: |
          lhapdf-management update --init
          pytest tests/regression_testing
