name: Check all PDFs

on: [push]

jobs:
  pdftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install lhapdf-management
        shell: bash -l {0}
        run: |
          python -m pip install .
          lhapdf-management update --init
      - name: Test alll
        shell: bash -l {0}
        run: |
          python tests/test_itall.py --yes --verbose
